### ISSUE TITLE
Fix/update grunt-packager link

### ISSUE THREAD

**Issue by ldexterldesign** [Sebastian-Fitzner/generator-veams#42]
Hey,

https://github.com/bobbor/grunt-packager link on http://www.prototype-generator.com/getting-started/plugins-and-modules.html is broken

Regards

**Comment by Sebastian-Fitzner** [comment]
Thx for the hint. 

It seems that bobbor deleted the repo so that I decided to delete this package in the next major release. 

Do you use this package?

**Comment by ldexterldesign** [comment]
Hey,

Apologies for delay

Nope

Regards
