### ISSUE TITLE
Why renaming the package?

### ISSUE THREAD

**Issue by Sebastian-Fitzner** [Sebastian-Fitzner/generator-veams#48]
Because the namespace `pg` is already in use :(. Therefore I decided to rename the packages to `veams` ...

**Comment by ldexterldesign** [comment]
:+1:

**Comment by Sebastian-Fitzner** [comment]
In short, each letter is the first literal of my two daughters names ;) 
V = Valerie
E = Emma
A = Amelie
M = Mara
S = Steinborn (surname)

**Comment by ldexterldesign** [comment]
![image](https://cloud.githubusercontent.com/assets/1715809/9743392/6f9d0c5c-5666-11e5-8a5e-dc3aec789722.png) :P
