### ISSUE TITLE
Missing examples on website

### ISSUE THREAD

**Issue by fussinatto** [Sebastian-Fitzner/generator-veams#49]
Examples are missing for [pg-methodology-components](http://www.prototype-generator.com/pg-methodology/pg-methodology-components.html) and [pg-methodology-blocks](http://www.prototype-generator.com/pg-methodology/pg-methodology-blocks.html)

**Comment by Sebastian-Fitzner** [comment]
jepp, 

the whole website is completely rebuild and will be published soon.
