### ISSUE TITLE
Review/fix SASS [Foundation] compilation

### ISSUE THREAD

**Issue by ldexterldesign** [Sebastian-Fitzner/generator-veams#50]
~ https://github.com/Sebastian-Fitzner/generator-veams/issues/44#issuecomment-137350746

Hey,

I'm desperately trying to get Foundation working and I think it may be connected to this lone build error - can you help?:

<img width="1440" alt="screen shot 2015-09-03 at 19 17 43" src="https://cloud.githubusercontent.com/assets/1715809/9665450/bb1fdc76-5270-11e5-8b8a-a363db5874a3.png">

In addition, other than the following, are there any other files I need to update in order to get Foundation working out of the box; and my SASS compiling?:

<img width="1440" alt="screen shot 2015-09-03 at 19 22 47" src="https://cloud.githubusercontent.com/assets/1715809/9665554/68a399c8-5271-11e5-8059-964c5b3a8c44.png">

```
/resources/bower-components/foundation/scss/foundation.scss
/resources/scss/styles.scss
```

To be clear I can run ```grunt``` without any errors, so I'm a little miffed as to why I can't get Foundation working:

<img width="1440" alt="screen shot 2015-09-03 at 19 28 28" src="https://cloud.githubusercontent.com/assets/1715809/9665677/0e2c4278-5272-11e5-9281-e763a39cfb8d.png">

Yours hopefully

**Comment by Sebastian-Fitzner** [comment]
Sry for the late response... Will take a Look this weekend...

**Comment by Sebastian-Fitzner** [comment]
Okay, that is a problem with the Gruntfile. Just use sass:dev in your gruntfile instead of sass:dist. Then it should be working ... Patch-Release is coming this week ...

**Comment by ldexterldesign** [comment]
Thanks for reply - much appreciate the help

Yep, that fixed one issue

Can you help fix the remaining [static mapping] issue?:
<img width="1440" alt="screen shot 2015-09-08 at 20 52 54" src="https://cloud.githubusercontent.com/assets/1715809/9744361/af15db48-566b-11e5-9d65-fa01f5ff3bad.png">

Yours hopefully

**Comment by Sebastian-Fitzner** [comment]
Yepp, that's why I created a new bug ticket. just delete `jshint` and `htmlhint` in `helpers/_grunt/concurrent.js`. That should solve the issue.

**Comment by ldexterldesign** [comment]
I have a clean build running but I have no clue how to import Foundation files

There is nothing about working with ```fileindex.js``` in the documentation?!:

* http://www.prototype-generator.com/pg-methodology/pg-methodology-css.html
* http://scss.prototype-generator.com/

Yours hopefully

**Comment by ldexterldesign** [comment]
Unless I've completly overlooked something [ https://www.npmjs.com/package/grunt-fileindex ]*

**Comment by Sebastian-Fitzner** [comment]
Okay, first of all, forget the website www.prototype-generator.com :). This site will be replaced (hopefully this weekend) and is outdated ... 

**Fileindex**
Fileindex is not used anymore in `Veams`. I've created a [`sass-globbing`](https://github.com/Sebastian-Fitzner/grunt-sass-globber) module to support this syntax: 

``` scss
@import "global/get-media";
@import "regions**/*";
@import "components/**/*";
@import "panels/**/*";
``` 

The module generates a new file with all imports included and this new file will be compiled (see `helpers/_grunt/sassGlobber.js` and `helpers/_grunt/sass.js`. 

The globbing file is `resources/scss/styles.scss` (with this file you are working) and the generated file is `resources/scss/styles.tmp.scss`. The generated file shows you all imports written-out. 

**Configurations and Settings**

All settings and variables are saved in `helpers/config.js`. I decided to separate all configs in an own file so that `Gulp` and `Grunt` can use them at the same time. 

All these things are documented on our new site ...

**Comment by ldexterldesign** [comment]
Hmm, so this is the only line I need to change to get Foundation working?:

```@import "../bower-components/foundation/scss/foundation"; // You can choose your specific components``` - resources/scss/styles.scss

If so can you help me out with the globbing syntax because the following isn't working:

```@import "../bower-components/foundation/scss/foundation/**/*";

Yours hopefully

**Comment by ldexterldesign** [comment]
Wondering if this is relevant https://github.com/zurb/foundation/issues/6201 ?

Regards

**Comment by Sebastian-Fitzner** [comment]
okay, do you have a git repo where I can take a look at it? that would be much faster ... 

In general you do not have to use sass-globbing for `foundation`. Just import the main `foundation` file. I will give it a try, too.

**Comment by ldexterldesign** [comment]
https://github.com/ldexterldesign/2048-shohreh_etemadi-seeb-website-20150219

Kind thanks

**Comment by Sebastian-Fitzner** [comment]
I added foundation support to you project. The only thing you missed, was to add a `_settings.scss` file for foundation. 

I haven't added such a file in the scaffolding process, because when foundation updates the package I need to update the generator too. 

To use foundation sass you should take a look at: http://foundation.zurb.com/docs/

**Comment by Sebastian-Fitzner** [comment]
Do you want to have a settings file already scaffolded in `Veams-Generator`, where all the options are commented out?

**Comment by ldexterldesign** [comment]
Great, cheers

Yea, my next question was going to be related to how to use ```settings.scss``` inside:
```
resources/scss/
```

Ideally we don't want to touch anything in:
```
resources/bower-components
```
... but still want a pipeline

Foundation uses all the ```settings.scss``` default variables - where would be locate the overrides?

Kind thanks

PS Yea, I'm familiar with Foundation https://github.com/zurb/foundation/issues?q=is%3Aissue+ldexterldesign+is%3Aclosed

**Comment by ldexterldesign** [comment]
> Do you want to have a settings file already scaffolded in Veams-Generator, where all the options are commented out?

Yea, I think so - anything uncommented would act as an override

Can you set this up in another PR (I'm still learning Grunt etc.) :/

Regards

**Comment by ldexterldesign** [comment]
Sorry, just seen this resources/scss/global/_settings.scss

Agreed

Regards

**Comment by Sebastian-Fitzner** [comment]
yeah I would suggest to add this to `_vars.scss` file. So you do not have two setting files.

**Comment by Sebastian-Fitzner** [comment]
I opened a new issue to add some basic configs when a new project will be scaffolded ... 
https://github.com/Sebastian-Fitzner/generator-veams/issues/52

**Comment by ldexterldesign** [comment]
I still can't get it working :(

No compilation when I try to glob:
```
@import "../bower-components/foundation/scss/foundation/components/**/*"; // You can choose your specific components  
```

Regards

**Comment by Sebastian-Fitzner** [comment]
Hmm, all components are included in `foundation.scss`. So you do not need any globbing for that. 

When you want to use globbing with external files (out from your scss directory), you need to modify `sassRoot` option in `helpers/_grunt/sassGlobber.js`. But I haven't tested such a use case with this module ;)

**Comment by ldexterldesign** [comment]
Yea, I thought so hence asking:
> Where is <%= paths.src %> defined?

It's a bit out of my depth ATM

I really need to get on with this project *cries*

Regards

**Comment by Sebastian-Fitzner** [comment]
> All settings and variables are saved in helpers/config.js. I decided to separate all configs in an own file so that Gulp and Grunt can use them at the same time.

![image](https://cloud.githubusercontent.com/assets/5232680/9794915/1abf3546-57ee-11e5-85ea-03c330f93f2c.png)

**Comment by ldexterldesign** [comment]
Can you show me a build with Foundation working?

I'm lost

Yours hopefully

**Comment by Sebastian-Fitzner** [comment]
I am lost, too :P. I thought your repo is already working? The pull request I created works fine. What exactly is the problem with your build?

**Comment by ldexterldesign** [comment]
Can you style a Foundation button with ```a.button``` with my repo'?

Cheers

**Comment by Sebastian-Fitzner** [comment]
of course... i give it a try ;)

**Comment by ldexterldesign** [comment]
1. http://quick.as/gQy5C9jwD
2. http://quick.as/GlPVi9Q7X
3. http://quick.as/Y0P5IzXAw

**Comment by Sebastian-Fitzner** [comment]
Hmm, hadn't any problems with that. Just tried it out and it works instantly ... Do you want to use mixins in scss or classes in your html?

**Comment by ldexterldesign** [comment]
We shouldn't need to do this once we've imported Foundation https://github.com/ldexterldesign/2048-shohreh_etemadi-seeb-website-20150219/blob/ea14b378e230d2223a78342487efc3d92c8b4640/resources/scss/global/_base.scss#L24

Foundation should own this class - we have all of the ```@import```s uncommented

Regards

**Comment by Sebastian-Fitzner** [comment]
Okay this issue is a foundation issue. After some debugging I came across some dependency problems. 

To solve the issue I just updated foundation to the newest version ... problem solved!

**Comment by Sebastian-Fitzner** [comment]
will update the package in `Veams-Generator` ...

**Comment by ldexterldesign** [comment]
Man, that's ridiculous - Foundation v5.2.0 is like 18 months old?!

Have you checked your other packages or shall I do it?

Thanks

**Comment by Sebastian-Fitzner** [comment]
The most packages I use are up to date. Foundation is not a package I am using ... Some colleagues in the company I work for use Foundation, but never mentioned a problem (They do not use classes). 

I will probably at `*` so that every you download ithe latest version...

**Comment by ldexterldesign** [comment]
Yep, the version update to have fixed it

Appreciate all your help today

Good luck with the weekend overhaul and if you need any [Foundation] input ping me a line

Kind thanks
