### ISSUE TITLE
Create/publish to https://pages.github.com/ without root index.html

### ISSUE THREAD

**Issue by ldexterldesign** [Sebastian-Fitzner/generator-veams#53]
https://github.com/ldexterldesign/2048-shohreh_etemadi-seeb-website-20150219

Hey,

As title

I've branched ```master``` to ```gh-pages``` but https://pages.github.com/ won't play nice:

> "Thanks for reaching out! GitHub Pages will look for the index.html file in the root of the repository -- It won't be able to build from an index.html file that is in a different folder."

I wondered  if this was a problem you've solved in the past, if so can you share a solution?

Yours hopefully

**Comment by ldexterldesign** [comment]
Is there a reason my ```_dist``` folder isn't populating?

Cheers

**Comment by ldexterldesign** [comment]
~ http://yeoman.io/learning/deployment.html

**Comment by ldexterldesign** [comment]
```$ git subtree push --prefix _output origin gh-pages``` solved this

I'm still curious why ```_dist``` exists?

Thanks

**Comment by Sebastian-Fitzner** [comment]
`_dist` exists to have a folder with version numbers (`grunt-version`). We can use this folder in our CI workflow (build plans etc.) ...

Thank you for the solution with `gh-pages`.
