### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by akhalizev** [Sebastian-Fitzner/generator-veams#58]
When I'm starting app with "gulp serve" it opens browser with this words.

**Comment by Sebastian-Fitzner** [comment]
Can you post your setup.json? 
I guess you didn't chose a template engine? So that's why there is no index.html which can be get ...

**Comment by akhalizev** [comment]
Yes, I don't have template engine:     "templateEngine": "",
What should I write there?

**Comment by Sebastian-Fitzner** [comment]
Sorry for the late response. In Gulp I haven't integrated a template engine yet, but I plan to support [gulp-hb](https://www.npmjs.com/package/gulp-hb) ... In the meantime just put your html files into a custom folder and sync this folder.
