### ISSUE TITLE
Gulp options lack templating

### ISSUE THREAD

**Issue by klokie** [Sebastian-Fitzner/generator-veams#60]
Hi, this looks like a very promising project! I'm just starting to get my head wrapped around the scaffolding options, but I was hoping to get up and running using my current favorite combo: Gulp + Bootstrap/SASS, using Handlebars templates via Assemble. However, it seems like the templating options are omitted when I choose Gulp as a task runner. Have I missed something?

**Comment by Sebastian-Fitzner** [comment]
Hi,

at this time I have to admit, that I hadn't paid much attention to upgrade the Gulp support. But it is on the roadmap. 

When you already have a working example with Gulp + Assemble I really like to take a look into it and integrate that into the generator. If not so, I will need the next week to establish a working solution ...

**Comment by Sebastian-Fitzner** [comment]
Hi klokie,

sorry for the late response but I was in parental leave for over a month. Now I am back in town ;). 

I have written a template engine called [Mangony](https://github.com/Sebastian-Fitzner/mangony). Is that something your are interested for Gulp? 
I will integrate this asap. Now we should discuss, wether Assemble is really necessary.

Kind regards

**Comment by klokie** [comment]
No worries – good for you for taking time off for children :)
I was able to get Veams and Grunt to do what I needed, and site rebuilds
take less than a second, so Gulp seems unnecessary at this point.
Mangony looks interesting. I'll look into it if & when I need to make a new
static site.
cheers

On Fri, May 13, 2016 at 7:13 AM, Sebastian Fitzner <notifications@github.com
> wrote:

> Hi klokie,
>
> sorry for the late response but I was in parental leave for over a month.
> Now I am back in town ;).
>
> I have written a template engine called Mangony
> <https://github.com/Sebastian-Fitzner/mangony>. Is that something your
> are interested for Gulp?
> I will integrate this asap. Now we should discuss, wether Assemble is
> really necessary.
>
> Kind regards
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Sebastian-Fitzner/generator-veams/issues/60#issuecomment-218953595>
>



-- 
// Daniel « Klokie » Grossfeld // +46 707298075 //
// ENLIVEN // *coming soon* // www.enliven.se //
// ODALÏSQUE Magazine // www.odalisquemagazine.com //

**Comment by Sebastian-Fitzner** [comment]
Now Veams provides Mangony as template engine for Grunt and Gulp
