### ISSUE TITLE
Remove unneccessary dependencies if exoskeleton is used

### ISSUE THREAD

**Issue by andy-gutsche** [Sebastian-Fitzner/generator-veams#76]
jquery, underscore, backbone

**Comment by andy-gutsche** [comment]
jQuery can be removed by adding the following to app.js:

Exoskeleton.View = require('backbone.nativeview');
Exoskeleton.ajax = require('backbone.nativeajax');

and 

"backbone.nativeajax": "^0.4.4",
"backbone.nativeview": "^0.3.3",

to package.json

**Comment by chaenu** [comment]
Hey,
I just initialized a new project with generator-veams: 7.6.1. I chose only jQuery as a JS framework, but there are references to VeamsQuery, Exoskeleton, Backbone in the app.js - which shouldn't be there and have to be deleted manually. I guess this relates to this issue?

**Comment by Sebastian-Fitzner** [comment]
You haven't checked Veams-JS? Can you post your setup.json?

**Comment by chaenu** [comment]
Yes, see my setup.json:
> {
  "generator-veams": {
    "projectName": "mangony update",
    "projectAuthor": "thomas",
    "selfContained": true,
    "taskRunner": [
      "grunt"
    ],
    "templateEngine": "mangony",
    "mangonyExpress": false,
    "installExtendedLayout": false,
    "installPlugin": false,
    "gulpModules": [],
    "gruntModules": [
      "grunt-browser-sync",
      "grunt-browserify",
      "grunt-version",
      "grunt-contrib-handlebars",
      "grunt-browserify",
      "grunt-contrib-uglify"
    ],
    "features": [
      "createDevFolder"
    ],
    "jsLibs": [
      "jquery"
    ],
    "cssLibs": [
      "lost-grid",
      "include-media"
    ],
    "testAndQA": false,
    "testAndQALibs": [],
    "veamsPackages": [
      "veamsMethodology",
      "veamsSCSS",
      "veamsJS"
    ],
    "docs": []
  }
}

**Comment by Sebastian-Fitzner** [comment]
yeah, if you check veams-js, it brings back every optional dependency for that. That's why you see the other packages back in your app.js. 

This will be changed with the new version of veams (Veams 5), but in the meantime you have to clean up your libs manually when you do not want to use them. It is the purpose the veams-js starter kit.

**Comment by chaenu** [comment]
Alright, thanks for the fast response!
